// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as DependencyVersion from "./DependencyVersion.bs.js";

function use(effect, dependency, shouldUpdate) {
  var version = DependencyVersion.use(dependency, shouldUpdate);
  React.useEffect((function () {
          return Curry._1(effect, undefined);
        }), [version]);
  
}

export {
  use ,
  
}
/* react Not a pure module */
