// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FreshLazyRef from "./FreshLazyRef.bs.js";

function use(supplier, dependency, shouldUpdate) {
  return FreshLazyRef.use(supplier, dependency, shouldUpdate).current;
}

export {
  use ,
  
}
/* FreshLazyRef Not a pure module */
