// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as DependencyChanged from "./DependencyChanged.bs.js";

function use(supplier, dependency, shouldUpdate) {
  var value = React.useRef(supplier);
  var dependencyChanged = DependencyChanged.use(dependency, shouldUpdate);
  if (dependencyChanged) {
    value.current = supplier;
  }
  return value.current;
}

export {
  use ,
  
}
/* react Not a pure module */
