// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Constant from "./Constant.bs.js";

function use(callback) {
  return Constant.use(function (param) {
              return callback;
            });
}

export {
  use ,
  
}
/* Constant Not a pure module */
