// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LazyRef from "./LazyRef.bs.js";

function use(supplier) {
  return LazyRef.use(supplier).current;
}

export {
  use ,
  
}
/* LazyRef Not a pure module */
