// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ConstantCallback from "./ConstantCallback.bs.js";

function use(param) {
  var match = React.useReducer((function (state, param) {
          return !state;
        }), false);
  var set = match[1];
  return ConstantCallback.use(function (param) {
              return Curry._1(set, undefined);
            });
}

export {
  use ,
  
}
/* react Not a pure module */
