// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as LazyRef from "./LazyRef.bs.js";

function use(supplier, dependency, shouldUpdate) {
  var value = LazyRef.use(supplier);
  var deps = React.useRef(dependency);
  if (Curry._2(shouldUpdate, deps.current, dependency)) {
    value.current = Curry._1(supplier, undefined);
    deps.current = dependency;
  }
  return value;
}

export {
  use ,
  
}
/* react Not a pure module */
