// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as LazyRef from "./LazyRef.bs.js";
import * as DependencyChanged from "./DependencyChanged.bs.js";

function use(supplier, dependency, shouldUpdate) {
  var value = LazyRef.use(supplier);
  var dependencyChanged = DependencyChanged.use(dependency, shouldUpdate);
  if (dependencyChanged) {
    value.current = Curry._1(supplier, undefined);
  }
  return value;
}

export {
  use ,
  
}
/* LazyRef Not a pure module */
