// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function use(supplier) {
  var ref = React.useRef(undefined);
  var value = ref.current;
  if (value !== undefined) {
    return value;
  }
  var value$1 = {
    current: Curry._1(supplier, undefined)
  };
  ref.current = value$1;
  return value$1;
}

export {
  use ,
  
}
/* react Not a pure module */
